use_frameworks!

platform :ios, '9.0'

target 'XHUniAppSDK_Example' do
  pod 'XHUniAppSDK', :path => '../'

  target 'XHUniAppSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
